//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {

        public BinhLuan(int maTV, int maSP, string content)
        {
            this.MaTV = maTV;
            this.MaSP = maSP;
            this.NoiDungBL = content;
        }

        public BinhLuan()
        {

        }
        public int MaBL { get; set; }
        public string NoiDungBL { get; set; }
        public int MaTV { get; set; }
        public int MaSP { get; set; }
    
        public virtual ThanhVien ThanhVien { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
