//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoSuuTap
    {

        public BoSuuTap()
        {

        }

        public BoSuuTap(int maTV, int maSP)
        {
            this.MaTV = maTV;
            this.MaSP = maSP;
        }

        public int MaBST { get; set; }
        public int MaSP { get; set; }
        public int MaTV { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
