//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonDatHang
    {

        public ChiTietDonDatHang(SanPhamGioHang product, int maDDH)
        {
            this.MaDDH = maDDH;

        }

        public ChiTietDonDatHang()
        {

        }
        public int MaChiTietDDH { get; set; }
        public int MaDDH { get; set; }
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual DonDatHang DonDatHang { get; set; }
    }
}
