//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamDacBiet
    {
        public int Ma { get; set; }
        public int MaSP { get; set; }
        public int GiamGia { get; set; }
        public bool UuThich { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
